
#ifndef GIZMO_CARTRIDGE_H
#define GIZMO_CARTRIDGE_H

#include "stdint.h"

#define CARTRIDGE_ROM_BANK_SIZE 16  // 16 KiB
#define CARTRIDGE_RAM_BANK_SIZE 8   // 8 KiB
#define CARTRIDGE_HEADER_TITLE_LEN 16

typedef enum cartridge_type_t cartridge_type_t;

enum cartridge_type_t {
    CARTRIDGE_TYPE_ROM_ONLY = 0x00,
    CARTRIDGE_TYPE_MBC1 = 0x01,
    CARTRIDGE_TYPE_MBC1_RAM = 0x02,
    CARTRIDGE_TYPE_MBC1_RAM_BATTERY = 0x03,
    CARTRIDGE_TYPE_MBC2 = 0x05,
    CARTRIDGE_TYPE_MBC2_BATTERY = 0x06,
    CARTRIDGE_TYPE_ROM_RAM = 0x08,
    CARTRIDGE_TYPE_ROM_RAM_BATTERY = 0x09,
    CARTRIDGE_TYPE_MMM01 = 0x0B,
    CARTRIDGE_TYPE_MMM01_RAM = 0x0C,
    CARTRIDGE_TYPE_MMM01_RAM_BATTERY = 0x0D,
    CARTRIDGE_TYPE_MBC3_TIMER_BATTERY = 0x0F,
    CARTRIDGE_TYPE_MBC3_TIMER_RAM_BATTERY = 0x10,
    CARTRIDGE_TYPE_MBC3 = 0x11,
    CARTRIDGE_TYPE_MBC3_RAM = 0x12,
    CARTRIDGE_TYPE_MBC3_RAM_BATTERY = 0x13,
    CARTRIDGE_TYPE_MBC5 = 0x19,
    CARTRIDGE_TYPE_MBC5_RAM = 0x1A,
    CARTRIDGE_TYPE_MBC5_RAM_BATTERY = 0x1B,
    CARTRIDGE_TYPE_MBC5_RUMBLE = 0x1C,
    CARTRIDGE_TYPE_MBC5_RUMBLE_RAM = 0x1D,
    CARTRIDGE_TYPE_MBC5_RUMBLE_RAM_BATTERY = 0x1E,
    CARTRIDGE_TYPE_MBC6 = 0x20,
    CARTRIDGE_TYPE_MBC7_SENSOR_RUMBLE_RAM_BATTERY = 0x22,
    CARTRIDGE_TYPE_POCKET_CAMERA = 0xFC,
    CARTRIDGE_TYPE_BANDAI_TAMA5 = 0xFD,
    CARTRIDGE_TYPE_HuC3 = 0xFE,
    CARTRIDGE_TYPE_HuC1_RAM_BATTERY = 0xFF,
};

#endif // GIZMO_CARTRIDGE_H